### ISSUE TITLE
Latest update breaks text formatting

### ISSUE THREAD

**Issue by Ultimushadow** [aratakileo/emogg#15]
### Describe the bug

Version 1.0-BETA.7-1.20.x breaks text formatting for some reason. I first noticed it in a large pack with other mods, but testing it in a controlled environment produced similar results. You can quite easily tell if the formatting is correct or not by sending a long command that is formatted incorrectly, it will show you an error message which is supposed to be all red, but only the first line is red - the rest of the message has no formatting. This extends, from what I could tell, to titles/subtitles as well, and although I did not check, I would imagine that any text which can use formatting like signs, books, item names, etc will also be broken.
Version 1.0-BETA.6-1.20.x works just fine, and does not produce the same results.

### Which side have you encountered the bug on?

Client

### Steps to reproduce

1. Download latest version of the mod
2. Type in a long command incorrectly
3. The command error shows up, but the second half is incorrectly formatted
4. You can text other types of text as necessary

### Additional context

My single mod testing pack has Better Log4j Config, DashLoader, Forge Config API Port, Mod Menu, Neruina, StackDeobfuscator, and YetAnotherConfigLib (mostly for testing and having libraries already ready to go when testing other mods)
If any of these is causing a conflict, I would not know, as I only test single/incompatible mods in this environment at minimum

**Comment by aratakileo** [comment]
You are absolutely right to notice! This bug appeared together with the implementation of a new text wrapping mechanism for the correct display of emojis in the text, which unfortunately breaks formatting. I intend to fix this problem soon.

**Comment by Ultimushadow** [comment]
Gotcha, I hope the fix is easy! I'll let you know if I find anything else in the current version as well

**Comment by aratakileo** [comment]
I would be very grateful if someone would help with fixing this problem. I had some difficulties with its 🥲

**Comment by aratakileo** [comment]
This issue has been fixed in version 1.0-BETA.8
