### ISSUE TITLE
random animation frames cannot be loaded

### ISSUE THREAD

**Issue by Useless6uy** [aratakileo/emogg#19]
### Describe the bug

Version: main (b3901ad879eb4e110713dd351a31b75861960eba, complied by me)

With the new update to the GIF implementation there seems to a small issue where random animated frames go missing.

Visually this looks like this:
![image2](https://github.com/aratakileo/emogg/assets/140262019/50747856-f176-4863-865c-6ae19ce714c2)

And this is the output in the console:
![image](https://github.com/aratakileo/emogg/assets/140262019/cbf7c9e7-b386-42f9-a856-5f0749150133)

* This seems to affect a random emote out of the about 3000 I am using and just a few frames.
* Most of the emote plays fine.
* The affected emote changes with every restart of the game.

### Which side have you encountered the bug on?

Client

### Steps to reproduce

1. Compile main branch
2. Start game with a resource pack with many animated emotes (I would provide the one I use but I do not have the rights to redistribute it, if more info is needed I can try and compile one I could share)
3. Check log, emotes picker and tab complete for errors

### Additional context

No mods used other than the ones necessary to load emogg.

**Comment by aratakileo** [comment]
Usually this is a failure that is corrected by reloading resources (re-entering the game, changing the list of resource packs used, changing the language). The next version will have a new animated emoji loading engine, it have to handle this much better

**Comment by Useless6uy** [comment]
Oh yeah, I'm aware.
This is with the new, unreleased emoji loading engine. It works amazingly otherwise.

I'll see if I can narrow the issue down further and maybe provide a fix.
I figure it might be a race condition because it occurs so infrequently.

**Comment by aratakileo** [comment]
I think so too
