### ISSUE TITLE
the scroll bar overflows the emote menu

### ISSUE THREAD

**Issue by Useless6uy** [aratakileo/emogg#20]
### Describe the bug

When scrolling down the emote menu with the mouse wheel the scrollbar overflows the emote menu:
![image](https://github.com/aratakileo/emogg/assets/140262019/35f4937f-a0e0-4e29-a852-5b52aca7afd4)

Dragging it works just fine:
![image](https://github.com/aratakileo/emogg/assets/140262019/61b7cf29-edd0-4d24-bb51-7e633c563068)

### Which side have you encountered the bug on?

Client

### Steps to reproduce

1. Start game with emogg 
2. Load only the Built-in emoji resource pack (to make it more visible)
3. Scroll down the emote menu with the scroll wheel

### Additional context

Tested with no additional mods and a self complied version of b3901ad879eb4e110713dd351a31b75861960eba.
I think this issue was present in previous versions too.

**Comment by aratakileo** [comment]
Yes, you're right, this bug was definitely in the last version. I will address this issue soon
