### ISSUE TITLE
When I send an emoji on a multiplayer server, I get kicked with "Received chat packet with missing or invalid signature".

### ISSUE THREAD

**Issue by creeper-0910** [aratakileo/emogg#24]
### Describe the bug

When I send an emoji on a multiplayer server, I get kicked with "Received chat packet with missing or invalid signature".

### Which side have you encountered the bug on?

Client

### Steps to reproduce

1.Log in to the server.
2.Add an emoji to the chat.
3.Kicked by server with "Received chat packet with missing or invalid signature".
...

### Additional context

I set "enforce-secure-profile" to false, but it did not solve the problem.

**Comment by aratakileo** [comment]
Have you sent only one emoji to the chat? Was it not sent along with any text?

**Comment by creeper-0910** [comment]
We use IgnisChat, a mod that converts romaji to Japanese, so the message is always sent with the converted message when sent.

**Comment by aratakileo** [comment]
I looked at the source code of the IgnisChat mod. It edits data packets with messages as soon as they arrive on the server. Probably the issue is related to this. I'll mark this issue as a conflict for now.

**Comment by aratakileo** [comment]
Check this out:
1. What happens if you send an emoji with a short name along with a presumably different number of kanji? With the least amount of kanji and with the most.
2. What happens if you just send an emoji without any text?

**Comment by creeper-0910** [comment]
1. If you include Kanji or Hiragana, any length of characters will be sent successfully.
2. It seems that IgnisChat automatically adds the conversion and outputs ":100: §6 (:100:)".

**Comment by aratakileo** [comment]
1. With emoji?
2. Doesn't look like something that could be fixed in emogg 🥲

**Comment by creeper-0910** [comment]
1. Yes
2. I will contact the author of IgnisChat. Thank you!

**Comment by aratakileo** [comment]
I have a question regarding the implementation of the IgnisChat system. Why is this system implemented on the server side? Are there any specific circumstances that do not allow you to implement this functionality on the client side?

**Comment by creeper-0910** [comment]
I don't know because I am not the author, but I suspect it is because I ported a plugin called LunaChat.

**Comment by aratakileo** [comment]
Can I contact you somehow to clarify the details regarding how the text is entered in Japanese and whether any features are implemented by Mojang? I have an idea of a possible more convenient implementation of the Japanese text input functionality in the client mod

**Comment by creeper-0910** [comment]
IgnisChat has a github repository. I believe you can contact the author here:
https://github.com/Pitan76/IgnisChat

**Comment by aratakileo** [comment]
あなたは私のことを間違って理解していました。 最適かつ便利な日本語テキスト入力システムを一緒に開発するため、連絡先を教えていただきたいとお願いしました。

**Comment by creeper-0910** [comment]
ごめんなさい、私はメールアドレスを公開していません....
TwitterのDMでも大丈夫でしょうか?

**Comment by aratakileo** [comment]
Discord で私を友達として追加してください: @aratakileo
