### ISSUE TITLE
[Suggestion] Link a twemoji resource pack in the description?

### ISSUE THREAD

**Issue by sisby-folk** [aratakileo/emogg#3]
hey hi! I made a twemoji resource pack using [Tigermouthbear/twemoji-named](https://github.com/Tigermouthbear/twemoji-named)

This is mostly 1:1 with discord's name for emojis, of course without the aliases and fuzzy search it has

![firefox_7mpzfWTJi8](https://github.com/aratakileo/emogg/assets/55819817/3bcc83bd-811d-4900-b4df-daeac2bfa8a0)

![image](https://github.com/aratakileo/emogg/assets/55819817/d9eb61ee-3531-4d35-88b7-4340b56527ef)

happy for this to be used and reused, it's all MIT stuff anyway: [twemogg.zip](https://github.com/aratakileo/emogg/files/11866073/twemogg.zip)

**Comment by aratakileo** [comment]
Wow, that's wonderful! You did it! This resource pack will become even better after the modification makes it possible to divide them into categories! In the meantime, I would like to add a link to it on the mod description pages on Modrinth and GitHub. The link will be added as a clickable banner, like the example resource pack, but with an indication of authorship.

Thank you so much for your contribution to the development of this modification! 🫶

**Comment by sisby-folk** [comment]
No problem! we just happened to know where to look ^^ feel free to do that.

**Comment by aratakileo** [comment]
By the way, I noticed you have a visual bug related to the header elements of the emoji selection menu. Please write with what scale of the interface and the resolution of the window (if in full-screen mode, then the monitor) these photos were taken. This information can help me fix the way it looks for you. Thank you in advance ^^

**Comment by sisby-folk** [comment]
GUI Scale 2 @ 1440p

**Comment by aratakileo** [comment]
Got it!

**Comment by aratakileo** [comment]
Now you can find your resourcepack on mod page:
https://modrinth.com/mod/emogg

**Comment by aratakileo** [comment]
If you suddenly missed this news, then I hasten to inform you that Twemogg are now part of the built-in resource packs in the mod! It can be disabled via the resource pack selection menu, just like a regular resource pack
