### ISSUE TITLE
emogg mod does not load on forge

### ISSUE THREAD

**Issue by Kaizuto** [aratakileo/emogg#35]
### Describe the bug

The mod doesn't load/run

### Which side have you encountered the bug on?

Client

### Steps to reproduce

1. Probably a mod conflict(?) but just install the emogg mod

### Additional context

![Not in the list](https://github.com/aratakileo/emogg/assets/83712471/ea771b07-c36a-4074-930b-5f4764c7dde2)
![Does not work at all](https://github.com/aratakileo/emogg/assets/83712471/b1916248-7287-48c7-a225-c9ae80878354)

**Comment by aratakileo** [comment]
Do you have the Sinytra Connector mod installed?

**Comment by Kaizuto** [comment]
Nope, i thought that wasn't a requirement?

**Comment by aratakileo** [comment]
It was. Sinytra Connector is signed there as `required`
