### ISSUE TITLE
Freeze when typing certain commands

### ISSUE THREAD

**Issue by unilock** [aratakileo/emogg#37]
### Describe the freeze

When typing certain commands, the client freezes until manually killed by the user.

### Which side have you encountered the freeze on?

Client

### What is your OS?

MacOS

### Steps to reproduce

1. Install Fabric Loader, Fabric API, and emogg
2. Start the game, join a world
3. Enter `/loot insert ~ ~ ~ fish`
4. Press the space bar
5. Game freezes

### Additional context

The only vanilla command I've managed to get this to happen with so far was `/loot`, and specifically only with the previously mentioned syntax, but it seems to occur more frequently with commands from other mods, such as `/spark` from [spark](https://modrinth.com/mod/spark).

It seems the problem occurs when Suggestions API starts generating suggestions? Since it only happens *after* inserting a space after the last argument in a given command.

This also occurs on Forge.

[`latest.log`](https://gist.github.com/unilock/ce60fdf1953d3bfc28ddeb96e339a30e#file-fabric-latest-log) from Fabric  
[`debug.log`](https://gist.github.com/unilock/ce60fdf1953d3bfc28ddeb96e339a30e#file-forge-debug-log) from Forge (has some more information; only Forge creates a `debug.log`)

**Comment by aratakileo** [comment]
Since you found out that the problem is in the Suggestions API, it was worth opening an issue about that in its repository 😅

Anyway, I'll see what I can do about it

**Comment by aratakileo** [comment]
The problem is in this line:
https://github.com/aratakileo/suggestions-api/blob/8a2ff21360cbd62d47781db44420020b0c52900a/general/src/main/java/io/github/aratakileo/suggestionsapi/mixin/CommandSuggestionsMixin.java#L86

I do not know how to fix this problem. So I'll probably just cut out this feature 🤷‍♂️
