### ISSUE TITLE
Emoji occasionally don't resolve if spammed

### ISSUE THREAD

**Issue by sisby-folk** [aratakileo/emogg#4]
Not entirely sure how to triage this one, but when spamming emoji from our twemoji pack in the new emoji picker menu, some emoji don't display in chat despite appearing in the input box. Nothing odd in the logs or anything.

![image](https://github.com/aratakileo/emogg/assets/55819817/d6f32745-e71c-4fa7-8d0e-0290ccd43a01)

**Comment by aratakileo** [comment]
Yes, that's right, there is such a bug and I know about it, as well as about some other bugs related to the emoji rendering engine in various interface environments. This bug, as well as other bugs that I mentioned, are rarely reproduced, and therefore I decided to return to them as soon as more important innovations and fixes for critical problems are completed, such as the possibility of separating emojis into categories and the problem you mentioned about the inability to launch the mod version 1.0-BETA.2 on Minecraft versions 1.19.x+

Even in spite of this, I am still grateful to you for letting me know about the problem you are facing. Thanks for that!

**Comment by aratakileo** [comment]
Hey! Your problem is fixed in Emogg v1.0-BETA.7! You can already check this out on Minecraft v1.20-1.20.1. Don't forget to unzip!
[[Donwload now]](https://github.com/aratakileo/emogg/files/12264426/emogg-1.0-BETA.7-1.20.x.zip)
