### ISSUE TITLE
Incompatibility with LibJF

### ISSUE THREAD

**Issue by Rafii2198** [aratakileo/emogg#40]
### Describe the bug

I tried to add this to my modpack and it just error out due to mixin injection failure. The log mentions LibJF, but I literally don't have time to test the whole modpack.

### Which side have you encountered the bug on?

Client

### Steps to reproduce

1. Use minecraft 1.20.2 fabric
2. Download latest LibJF and emogg
3. Try to launch the game

### Logs

https://mclo.gs/wFdKb1l

**Comment by aratakileo** [comment]
This problem has been described in #36 and has been fixed in Emogg version 2.0.0. However, this version is not available for Minecraft 1.20.2. I will try to make it available in the next Emogg version 🤷‍♂️

**Comment by Rafii2198** [comment]
Oh I had to get confused, I am playing on 2 modpacks, one on 1.20.2 and one on 1.20.1 and I thought I downloaded emogg 2.0.0 on both of them... my bad

**Comment by aratakileo** [comment]
And, the problem that you described is in LibJF, because if you run only it then there will still be an error:
https://mclo.gs/YcGqkHh

**Comment by Rafii2198** [comment]
I just tried it and the issue doesn't prevent the game from starting, it launched and worked fine. But I will report that to the author.
