### ISSUE TITLE
Crash at chat Screen and Config Screen (BETA.3-19.1-1.19.3)

### ISSUE THREAD

**Issue by CryroFox** [aratakileo/emogg#6]
Opening Chat Screen:
https://mclo.gs/Tve6BeS

Opening the Config Screen:
https://mclo.gs/loDFtoq

**Comment by aratakileo** [comment]
Thank you so much for your feedback! I'm already know about this problem and I'm working on it. I'll be back to you soon with a new answer!

**Comment by aratakileo** [comment]
I'm back with the answer! The problem is solved in the 1.0-BETA.4 version of the mod. I also inform you that from now on, mod updates for versions 1.19.1-1.19.3 will no longer be released due to difficulties associated with adapting the mod code to these versions 😓

**Comment by CryroFox** [comment]
Thank you so much!
And I absolutely understand not wanting to continue back-porting to 1.19
