### ISSUE TITLE
duplicate file on modrinth

### ISSUE THREAD

**Issue by sisby-folk** [aratakileo/emogg#7]
the beta-4 version has a duplicate file with the same name: https://modrinth.com/mod/emogg/version/1.0-BETA.4

kind of a modrinth bug for allowing that to happen

unclear if both versions work - but it makes some version managers and modpack tools go haywire.

**Comment by aratakileo** [comment]
Thank you for reporting this specific issue! To help solve this issue, I have left only one file for this version. There shouldn't be a problem now 😄
