### ISSUE TITLE
(Suggestion) Logging config setting

### ISSUE THREAD

**Issue by Ultimushadow** [aratakileo/emogg#9]
Hey there, I was wondering if you could add a config option to disable the mod's log output when typing, looks like this:
[Render thread/INFO]: Process: CommandSuggestionsMixin
I looked for a setting and wasn't able to find one, and I don't _think_ this is one of my mods as I launched it with just Mod Menu and Neruina
It really clutters up the log and isn't really needed for my purposes, whereas the other things in the log are, so I was hoping you could add an option to disable it? I'm currently testing a pack so I assume this is logging clientside as I haven't tested on a server, but if it's also logging on the server that's even worse as I quite frequently check server logs. A new line for every letter typed is juuust a bit too much 😅 let me know if this is something you can do!

**Comment by aratakileo** [comment]
Heey! Can you please tell me which version of the mod you are playing with? Please provide the full name of the version 👉👈

**Comment by Ultimushadow** [comment]
Oh, my bad that should have been the first thing I mentioned, I'll double check but when I tested it by itself I was using Prism and downloaded the latest update available through Modrinth like.. ten minutes before I wrote this out. I'm gonna uh, check that in a couple hours though, I've been up for over 24 hours (hence me missing the mod version) so I'll get a definitive version number when I'm not actively dying 🥲

**Comment by aratakileo** [comment]
Please don't die until we figure out what the problem is 🥲

**Comment by aratakileo** [comment]
I can help you in determining the version. Which version of Minecraft did you download the mod for?

**Comment by Ultimushadow** [comment]
1.20.1 latest version of fabric

**Comment by aratakileo** [comment]
Thank you, now I understand on which version you have this problem! However, you are still not allowed to die 👋

**Comment by Ultimushadow** [comment]
I'll try to keep it in check 😅 😴

**Comment by aratakileo** [comment]
Very nice of you! 😎

**Comment by aratakileo** [comment]
If you need to solve this problem as soon as possible, then you can [download the fixed version of the mod right now (don't forget to unzip!)](https://github.com/aratakileo/emogg/files/12173382/emogg-1.0-BETA.5-1.20.x.zip). After more new features appear in the mod, the version with your fix will be published on modrinth. Have a nice game! ☺️

**Comment by Ultimushadow** [comment]
Thanks for the quick fix! I love how this mod works so I'm pretty glad to be able to use it more cleanly 🥳

**Comment by aratakileo** [comment]
You're welcome 🤗
